'use client';
import { useState, useEffect } from 'react';
import { getUiTranslations } from '../lib/i18nClient';

/**
 * EmailReport Component
 * Allows users to email reports to stakeholders with customizable message
 * Supports 207 languages via dynamic translation
 */

const BASE_UI = {
  emailReport: 'Email Report',
  toLabel: 'To (comma-separated)',
  ccLabel: 'CC (optional)',
  subjectLabel: 'Subject',
  messageLabel: 'Message',
  includeAttachment: 'Include report as attachment',
  scheduleDelivery: 'Schedule delivery',
  scheduledTime: 'Delivery time',
  send: 'Send',
  sending: 'Sending...',
  sent: 'Email Sent Successfully!',
  recipientPlaceholder: 'email@example.com, another@example.com',
  defaultSubject: 'Sovereign Intelligence Report',
  defaultMessage: 'Please find attached the latest intelligence report generated by Sovereign AI.',
  errorNoRecipient: 'Please enter at least one recipient email',
  errorSendFailed: 'Failed to send email',
  cancel: 'Cancel',
};

const RTL_LANGUAGES = ['Arabic', 'Hebrew', 'Urdu', 'Persian', 'Pashto', 'Sindhi'];

export default function EmailReport({ reportHtml, reportTitle, verticalId, color = '#3b82f6', lang = 'English' }) {
  const [ui, setUi] = useState(BASE_UI);
  const [isOpen, setIsOpen] = useState(false);
  const [sending, setSending] = useState(false);
  const [sent, setSent] = useState(false);
  const [error, setError] = useState(null);
  
  const [recipients, setRecipients] = useState('');
  const [cc, setCc] = useState('');
  const [subject, setSubject] = useState(reportTitle || BASE_UI.defaultSubject);
  const [message, setMessage] = useState(BASE_UI.defaultMessage);

  const isRTL = RTL_LANGUAGES.includes(lang);

  // Load translations
  useEffect(() => {
    (async () => {
      try {
        const { t } = await getUiTranslations({
          base: BASE_UI,
          lang,
          cachePrefix: 'SI_EmailReport',
          setDir: false,
        });
        setUi(t || BASE_UI);
        if (t) {
          setSubject(reportTitle || t.defaultSubject);
          setMessage(t.defaultMessage);
        }
      } catch (err) {
        console.warn('EmailReport translation failed:', err);
      }
    })();
  }, [lang, reportTitle]);
  const [includeAttachment, setIncludeAttachment] = useState(true);
  const [scheduleDelivery, setScheduleDelivery] = useState(false);
  const [scheduledTime, setScheduledTime] = useState('');

  const handleSend = async () => {
    if (!recipients.trim()) {
      setError('Please enter at least one recipient email');
      return;
    }

    setSending(true);
    setError(null);

    try {
      const res = await fetch('/api/reports/email', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          recipients: recipients.split(',').map(e => e.trim()).filter(Boolean),
          cc: cc.split(',').map(e => e.trim()).filter(Boolean),
          subject,
          message,
          reportHtml: includeAttachment ? reportHtml : null,
          reportTitle,
          verticalId,
          lang,
          scheduled: scheduleDelivery ? scheduledTime : null,
        }),
      });

      if (!res.ok) throw new Error('Failed to send email');
      
      setSent(true);
      setTimeout(() => {
        setIsOpen(false);
        setSent(false);
      }, 2000);
    } catch (err) {
      setError(err.message || ui.errorSendFailed);
    } finally {
      setSending(false);
    }
  };

  if (!isOpen) {
    return (
      <button
        onClick={() => setIsOpen(true)}
        style={{
          padding: '8px 16px',
          borderRadius: 8,
          background: `${color}20`,
          border: `1px solid ${color}40`,
          color: '#fff',
          cursor: 'pointer',
          display: 'flex',
          alignItems: 'center',
          gap: 8,
          fontSize: 14,
          fontWeight: 500,
          direction: isRTL ? 'rtl' : 'ltr',
        }}
      >
        📧 {ui.emailReport}
      </button>
    );
  }

  return (
    <div style={{
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: 'rgba(0,0,0,0.8)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 9999,
      padding: 20,
    }}>
      <div style={{
        background: 'linear-gradient(135deg, #1a2942 0%, #0d1a2d 100%)',
        borderRadius: 16,
        padding: 32,
        maxWidth: 500,
        width: '100%',
        border: `1px solid ${color}30`,
        maxHeight: '90vh',
        overflowY: 'auto',
        direction: isRTL ? 'rtl' : 'ltr',
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }}>
          <h2 style={{ color: '#fff', margin: 0, fontSize: 20, display: 'flex', alignItems: 'center', gap: 10 }}>
            📧 {ui.emailReport}
          </h2>
          <button onClick={() => setIsOpen(false)} style={{ background: 'none', border: 'none', color: 'rgba(255,255,255,0.6)', fontSize: 24, cursor: 'pointer' }}>×</button>
        </div>

        {sent ? (
          <div style={{ textAlign: 'center', padding: 40 }}>
            <div style={{ fontSize: 48, marginBottom: 16 }}>✅</div>
            <div style={{ color: '#10b981', fontSize: 18, fontWeight: 600 }}>{ui.sent}</div>
          </div>
        ) : (
          <div style={{ display: 'grid', gap: 16 }}>
            {/* Recipients */}
            <div>
              <label style={{ color: 'rgba(255,255,255,0.7)', fontSize: 13, marginBottom: 6, display: 'block' }}>
                {ui.toLabel} *
              </label>
              <input
                type="text"
                value={recipients}
                onChange={(e) => setRecipients(e.target.value)}
                placeholder={ui.recipientPlaceholder}
                style={{
                  width: '100%',
                  padding: '12px 16px',
                  borderRadius: 8,
                  background: 'rgba(0,0,0,0.3)',
                  border: '1px solid rgba(255,255,255,0.1)',
                  color: '#fff',
                  fontSize: 14,
                }}
              />
            </div>

            {/* CC */}
            <div>
              <label style={{ color: 'rgba(255,255,255,0.7)', fontSize: 13, marginBottom: 6, display: 'block' }}>
                {ui.ccLabel}
              </label>
              <input
                type="text"
                value={cc}
                onChange={(e) => setCc(e.target.value)}
                placeholder="cc@example.com"
                style={{
                  width: '100%',
                  padding: '12px 16px',
                  borderRadius: 8,
                  background: 'rgba(0,0,0,0.3)',
                  border: '1px solid rgba(255,255,255,0.1)',
                  color: '#fff',
                  fontSize: 14,
                }}
              />
            </div>

            {/* Subject */}
            <div>
              <label style={{ color: 'rgba(255,255,255,0.7)', fontSize: 13, marginBottom: 6, display: 'block' }}>
                Subject
              </label>
              <input
                type="text"
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
                style={{
                  width: '100%',
                  padding: '12px 16px',
                  borderRadius: 8,
                  background: 'rgba(0,0,0,0.3)',
                  border: '1px solid rgba(255,255,255,0.1)',
                  color: '#fff',
                  fontSize: 14,
                }}
              />
            </div>

            {/* Message */}
            <div>
              <label style={{ color: 'rgba(255,255,255,0.7)', fontSize: 13, marginBottom: 6, display: 'block' }}>
                Message
              </label>
              <textarea
                value={message}
                onChange={(e) => setMessage(e.target.value)}
                rows={4}
                style={{
                  width: '100%',
                  padding: '12px 16px',
                  borderRadius: 8,
                  background: 'rgba(0,0,0,0.3)',
                  border: '1px solid rgba(255,255,255,0.1)',
                  color: '#fff',
                  fontSize: 14,
                  resize: 'vertical',
                }}
              />
            </div>

            {/* Options */}
            <div style={{ display: 'flex', gap: 20, flexWrap: 'wrap' }}>
              <label style={{ display: 'flex', alignItems: 'center', gap: 8, color: 'rgba(255,255,255,0.8)', fontSize: 14, cursor: 'pointer' }}>
                <input
                  type="checkbox"
                  checked={includeAttachment}
                  onChange={(e) => setIncludeAttachment(e.target.checked)}
                  style={{ width: 18, height: 18, accentColor: color }}
                />
                Include report as attachment
              </label>
              <label style={{ display: 'flex', alignItems: 'center', gap: 8, color: 'rgba(255,255,255,0.8)', fontSize: 14, cursor: 'pointer' }}>
                <input
                  type="checkbox"
                  checked={scheduleDelivery}
                  onChange={(e) => setScheduleDelivery(e.target.checked)}
                  style={{ width: 18, height: 18, accentColor: color }}
                />
                Schedule delivery
              </label>
            </div>

            {/* Schedule Time */}
            {scheduleDelivery && (
              <div>
                <label style={{ color: 'rgba(255,255,255,0.7)', fontSize: 13, marginBottom: 6, display: 'block' }}>
                  Scheduled Time
                </label>
                <input
                  type="datetime-local"
                  value={scheduledTime}
                  onChange={(e) => setScheduledTime(e.target.value)}
                  style={{
                    width: '100%',
                    padding: '12px 16px',
                    borderRadius: 8,
                    background: 'rgba(0,0,0,0.3)',
                    border: '1px solid rgba(255,255,255,0.1)',
                    color: '#fff',
                    fontSize: 14,
                  }}
                />
              </div>
            )}

            {/* Error */}
            {error && (
              <div style={{ background: 'rgba(239,68,68,0.1)', border: '1px solid rgba(239,68,68,0.3)', borderRadius: 8, padding: 12, color: '#ef4444', fontSize: 14 }}>
                {error}
              </div>
            )}

            {/* Actions */}
            <div style={{ display: 'flex', gap: 12, marginTop: 8 }}>
              <button
                onClick={() => setIsOpen(false)}
                style={{
                  flex: 1,
                  padding: '12px 20px',
                  borderRadius: 8,
                  background: 'rgba(255,255,255,0.1)',
                  border: '1px solid rgba(255,255,255,0.2)',
                  color: '#fff',
                  cursor: 'pointer',
                  fontSize: 14,
                  fontWeight: 500,
                }}
              >
                Cancel
              </button>
              <button
                onClick={handleSend}
                disabled={sending}
                style={{
                  flex: 1,
                  padding: '12px 20px',
                  borderRadius: 8,
                  background: sending ? 'rgba(59,130,246,0.5)' : color,
                  border: 'none',
                  color: '#fff',
                  cursor: sending ? 'not-allowed' : 'pointer',
                  fontSize: 14,
                  fontWeight: 600,
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  gap: 8,
                }}
              >
                {sending ? (
                  <>
                    <span style={{ animation: 'spin 1s linear infinite', display: 'inline-block' }}>⏳</span>
                    Sending...
                  </>
                ) : (
                  <>📤 {scheduleDelivery ? 'Schedule' : 'Send Now'}</>
                )}
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
